Implement Dan Heng Imbibitor Lunae
simimpact/srsim pull request #227
Opened 2023-09-17 18:46 UTC by interfacew

2023-09-24 14:31 UTC, Vessv requested changes
For now this is what i could find in a bit of time, there might be others things.

2023-09-24 14:31 UTC, Vessv commented on internal/character/danhengimbibitorlunae/attack.go
> +			BaseDamage:   info.DamageMap{model.DamageFormula_BY_ATK: enhancedAtk2[c.info.AttackLevelIndex()*3/19]},
3/19 Fraction is inside the array index.

2023-09-24 14:31 UTC, Vessv commented on internal/character/danhengimbibitorlunae/attack.go
> +			BaseDamage:   info.DamageMap{model.DamageFormula_BY_ATK: enhancedAtk3[c.info.AttackLevelIndex()*9/25]},
9/25 Fraction is inside the array index

2023-09-24 14:31 UTC, Vessv commented on internal/character/danhengimbibitorlunae/ult.go
> +			BaseDamage:   info.DamageMap{model.DamageFormula_BY_ATK: ult[c.info.UltLevelIndex()*7/15]},
7/15 fraction is inside the Array Index.
```suggestion
			BaseDamage:   info.DamageMap{model.DamageFormula_BY_ATK: ult[c.info.UltLevelIndex()]*7/15},
```

2023-09-24 14:31 UTC, Vessv commented on internal/character/danhengimbibitorlunae/ult.go
> +		c.engine.InsertAction(c.id)
ImbibitorLunae E2 is 100% advance forward, not InsertAction. You need to use ModifyGaugeNormalized for this case, next is a suggestion but its not complete, i would advice you to look at other implementations to see how they did it and adapt it for this case.
```suggestion
		c.engine.ModifyGaugeNormalized(info.ModifyAttribute{
					Key:    ,
					Target: c.id,
					Source: c.id,
					Amount: -1,
				})
```

2023-09-25 17:11 UTC, Vessv commented on internal/character/danhengimbibitorlunae/trace.go
> +func A6OnAfterHit(mod *modifier.Instance, e event.HitEnd) {
A6OnAfterHit func is not needed. A6OnBeforeHit only works for the hit so it will not affect Dan stats.

2023-09-25 17:11 UTC, Vessv commented on internal/character/danhengimbibitorlunae/skill.go
> +		Source: c.id,
Outroar buff has `"LifeStepImmediately": true` in config. In this case, when you call AddModifier you need to add the `TickImmediately: true`
```suggestion
		Source: c.id,
		TickImmediately: true
```

2023-09-25 18:41 UTC, Vessv reviewed
Some other things i could find. As beofre, there are some suggestions, always check if the code makes sense lol(surely i didn't mess smt up).

2023-09-25 18:41 UTC, Vessv commented on internal/character/danhengimbibitorlunae/skill.go
> +	if c.info.Eidolon < 4 {
Remove the conditional and just do one Register, when AddModifier is called for SkillEffect, check if E4 then Duration = 2 and finally add  Duration inside the info.Modifier. In this case the AddModifier for this modifier is in the AddSkill function.

This is how the Register would look like here.
```
modifier.Register(SkillEffect, modifier.Config{
			StatusType: model.StatusType_STATUS_BUFF,
			Stacking: modifier.ReplaceBySource,
			TickMoment: modifier.ModifierPhase2End
			MaxCount: 4,
			Duration: 1,
			Listeners: modifier.Listeners{
				OnAdd: SkillOnAdd,
			},
			CountAddWhenStack: 1,
		})
```

2023-09-25 18:41 UTC, Vessv commented on internal/character/danhengimbibitorlunae/skill.go
> +	c.engine.AddModifier(c.id, info.Modifier{
Here is where the Outroar duration would be checked and if dan is E4 then duration = 2.
```suggestion
        outroarDuration := 1
	if c.info.Eidolon >= 4 {
	     outroarDuration = 2
	}
	
	c.engine.AddModifier(c.id, info.Modifier{
```
 then inside the info.Modifier you would set the duration to outroarDuration
``` go
Duration: outroarDuration
```

2023-09-25 18:41 UTC, Vessv commented on internal/character/danhengimbibitorlunae/skill.go
> +func SkillOnPhase2(mod *modifier.Instance) {
func SkillOnPhase2 can be removed.

2023-09-25 18:41 UTC, Vessv commented on internal/character/danhengimbibitorlunae/attack.go
> +			c.AddSkill()
OutRoar only works for Divine Spear or Fulgurant Leap (Lv 2 and 3 of basic), so this is conditional is better to remove it from here (Normal Basic)
```suggestion	
```

2023-09-25 18:41 UTC, Vessv commented on internal/character/danhengimbibitorlunae/attack.go
> +			c.AddSkill()
OutRoar only works for Divine Spear or Fulgurant Leap (Lv 2 and 3 of basic), so this is conditional is better to remove it from here (Lv 1 Basic)
```suggestion	
```

2023-09-26 15:29 UTC, Vessv reviewed
This are some other things i found.
Another thing is, i think you need to check all the modifiers you implemented and only add `StatusType: ` when its a explicit buff or debuff. For example, i think the A4 modifier doesn't have that in datamine, so its prob better to remove it.

2023-09-26 15:29 UTC, Vessv commented on internal/character/danhengimbibitorlunae/ult.go
> +		StatusType:        model.StatusType_STATUS_BUFF,
Squama Sacrosancta in datamine is  "StatusType": "Other", i think in this case the `StatusType:` need to be removed.
```suggestion
```

2023-09-26 16:25 UTC, interfacew commented
in the game, when dan unleash an enhanced attack, there is only 1 action.
but in this code, it used multi action(1 attack and 1-3 skill).

also in game, use the skill of dan won't trigger skill listener like yukong trace 103 to generate energy.

how can i fix this?

(sorry for my bad English)

2023-09-26 16:37 UTC, Vessv commented on internal/character/danhengimbibitorlunae/skill.go
> +	modifier.Register(EnhanceLevel, modifier.Config{
Keeping track of the `EnhanceLevel` via a modifier is not really needed. 

> so give char some like skillCount variable that you just increment every time skill is used and then set to 0 in Attack 
-Kyle

2023-09-26 16:37 UTC, Vessv commented on internal/character/danhengimbibitorlunae/ult.go
> +	modifier.Register(Point, modifier.Config{
Same as the `EnhancheLevel` Modifier. Keeping track of the `Point` via a modifier is not really needed. My suggestion instead would be to just use a variable , give there char some like `Point`variable that you just increment after ult then change it in Attack. Bscly what you are doing with with the `Point` modifier, but change to a variable and not a modifier.

2023-09-26 16:54 UTC, Vessv commented
> in the game, when dan unleash an enhanced attack, there is only 1 action. but in this code, it used multi action(1 attack and 1-3 skill).
> 
> also in game, use the skill of dan won't trigger skill listener like yukong trace 103 to generate energy.
> 
> how can i fix this?
> 
> (sorry for my bad English)

Hi, no worries, i am also a non native english speaker.
I also am not sure how 💀 
But from what Kyle told me

> from a sim perspective, we dont care about the internal distinction of multi actions like how it is implemented in game (at least not right now, though there is an argument to be made that we should). QQ is another case off the top of my head that has multiple skills technically. As long as the behavior is there, it doesn't materially matter what the action is since we do not have any "action keys"
The current implementation is definitely "incorrect" because of the whole "skill would count as an action" stuff, but that's okay because materially the implementation of DHIL should not change when that is fixed. It is okay to have the "incorrect" implementation merged it and then someone can follow up with the core changes necessary to support it
-Kyle

So don't worry about that for now, i think.

2023-09-27 15:15 UTC, Vessv reviewed
This are the last changes i could find. 
This is just to replicate how the game does it and so it doesn't buff other attacks like Tingyun additional(pursued) attack.

2023-09-27 15:15 UTC, Vessv commented on internal/character/danhengimbibitorlunae/eidolon.go
> +		StatusType: model.StatusType_STATUS_BUFF,
E6 effect is a modifier that listen to OnBeforeHitAll and check if the attacks is lvl 3 then adds the res pen to that attack
```suggestion
		StatusType: model.StatusType_STATUS_BUFF,
		MaxCount: 3,
		CountAddWhenStack: 1,
		Stacking: modifier.ReplaceBySource,
		Listeners: modifier.Listeners{
			OnBeforeHitAll: E6PenOnBeforeHitAll,
			OnAfterAttack: E6PenOnAfterAttack,
		}
```
The beforehit function would look something like this.
```
func E6PenOnBeforeHitAll(mod *modifier.Instance, e event.HitStart) {
	if //check here if attack level is 3 {
		amt := mod.Count()*mod.State().(float64)
		e.Hit.Attacker.AddProperty(name, prop.ImaginaryPEN, amt)
	}
}
```
The afterattack function would look something like this.
```
func E6PenOnAfterAttack(mod *modifier.Instance, e event.AttackEnd) {
	if //check here if attack level is 3 {
		//remove E6Effect mod
	}
}
```

2023-09-27 15:15 UTC, Vessv commented on internal/character/danhengimbibitorlunae/eidolon.go
> +		c.E6Count++
Here is where you need to add de E6Effect modifier, i think you dont need to E6Count bc the mod will only stack upto 3.
You will also need to check here if
```
if c.info.Eidolon >= 6 {
			//Add E6Effect modifier, the state would be 0.2 
		}
```

2023-09-28 14:05 UTC, Vessv approved these changes
👍

2023-09-28 14:08 UTC, merged