Trailblazer (Imaginary)
simimpact/srsim pull request #293
Opened 2024-09-30 18:51 UTC by interfacew

2024-09-30 19:09 UTC, interfacew commented
is there a better solution for e4?

2024-09-30 19:19 UTC, interfacew commented
are there any other ways to handle e4?

2024-10-05 17:53 UTC, interfacew commented on internal/character/trailblazerimaginary/talent.go
> +			OnBeforeHit: superBreakListener,
im now using a modifier on enemies to track stance damage, will it be better to use a map in `BackupDancer` to record this?

2024-11-17 13:48 UTC, kdovtdc requested changes
small fixes, otherwise seems functional with existing structure. I would leave as is and come back in the future when potentially proper support + other stuff needed for Superbreak (or better handling thereof) is added

2025-01-16 16:41 UTC, closed without merging